spring.application.name=sei
spring.flyway.schemas=sei_db
spring.flyway.default-schema=sei_db

# DataSource (PostgreSQL)
spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
app.admin.password=${DB_KEY_CRIPTO:}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (HikariCP - padrao do Spring Boot)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false

# Actuator
management.endpoints.web.exposure.include=health,info,flyway
management.endpoint.health.show-details=when-authorized