-- ALTERAÇÃO DE TIPO DE DADO DE CGM -> INTEGER PARA VARCHAR
ALTER TABLE sei_db.aluno
ALTER COLUMN cgm TYPE VARCHAR(10);

-- RETIRAR OBRIGATORIEDADE DE EXISTÊNCIA DA COLUNA jogo_id_jogo na TABELA sala
ALTER TABLE sei_db.sala
ALTER COLUMN jogo_id_jogo DROP NOT NULL;