-- ADICIONA COLUNA sala_id_sala NA TABELA aluno PARA PROPORCIONAR MAIOR RELACIONAMENTO ENTRE ENTIDADES
ALTER TABLE aluno ADD COLUMN sala_id_sala INTEGER;
ALTER TABLE aluno ADD CONSTRAINT fk_aluno_sala
    FOREIGN KEY (sala_id_sala) REFERENCES sala(id_sala);